#!/bin/bash

cd $GOPATH/src/github.com/subtalime/go-evepraisal
pwd
ls -l
echo "CLONE ..."
git clone https://github.com/Subtalime/go-evepraisal.git . 
export GO111MODULE=on ENV=prod 
echo "SETUP ..."
make setup 

echo "BUILD ..."
make build 
echo "INSTALL ..."
make install 

echo "DONE..."
mkdir /evepraisal/ 
mv $GOPATH/bin/evepraisal /evepraisal/evepraisal 
# if we RM, we can't /bin/bash
# rm -rf $GOPATH 
apk del build-dependencies 
mkdir /evepraisal/db
cd /evepraisal
which bash
./evepraisal

#WORKDIR /evepraisal/
#CMD ["./evepraisal"]
